<?php

namespace Database\Seeders;

use App\Models\PageComponent;
use Illuminate\Database\Seeder;

/**
 * Seeds the default page builder components.
 */
class PageComponentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $components = [
            // Layout components
            [
                'name' => 'Hero Section',
                'slug' => 'hero',
                'category' => 'layout',
                'description' => 'A large hero section with heading, subheading, and call-to-action buttons',
                'icon' => 'layout',
                'vue_component' => 'HeroSection.vue',
                'default_props' => [
                    'heading' => 'Welcome to Our Site',
                    'subheading' => 'Discover amazing things with us',
                    'primaryButtonText' => 'Get Started',
                    'primaryButtonLink' => '#',
                    'secondaryButtonText' => 'Learn More',
                    'secondaryButtonLink' => '#',
                    'backgroundImage' => null,
                    'overlayOpacity' => 50,
                    'alignment' => 'center',
                ],
                'prop_schema' => [
                    'heading' => ['type' => 'text', 'label' => 'Heading'],
                    'subheading' => ['type' => 'textarea', 'label' => 'Subheading'],
                    'primaryButtonText' => ['type' => 'text', 'label' => 'Primary Button Text'],
                    'primaryButtonLink' => ['type' => 'page_link', 'label' => 'Primary Button Link'],
                    'secondaryButtonText' => ['type' => 'text', 'label' => 'Secondary Button Text'],
                    'secondaryButtonLink' => ['type' => 'page_link', 'label' => 'Secondary Button Link'],
                    'backgroundImage' => ['type' => 'hero_image', 'label' => 'Background Image'],
                    'overlayOpacity' => ['type' => 'range', 'label' => 'Overlay Opacity', 'min' => 0, 'max' => 100, 'step' => 5, 'suffix' => '%'],
                    'alignment' => ['type' => 'select', 'label' => 'Alignment', 'options' => ['left', 'center', 'right']],
                ],
                'sort_order' => 1,
            ],
            [
                'name' => 'Two Column Layout',
                'slug' => 'two-column-layout',
                'category' => 'layout',
                'description' => 'A flexible two-column layout with customizable widths',
                'icon' => 'columns',
                'vue_component' => 'TwoColumnLayout.vue',
                'default_props' => [
                    'leftWidth' => '50%',
                    'rightWidth' => '50%',
                    'gap' => '2rem',
                    'reverseOnMobile' => false,
                    'leftContent' => [],
                    'rightContent' => [],
                ],
                'prop_schema' => [
                    'leftWidth' => ['type' => 'text', 'label' => 'Left Column Width'],
                    'rightWidth' => ['type' => 'text', 'label' => 'Right Column Width'],
                    'gap' => ['type' => 'text', 'label' => 'Gap'],
                    'reverseOnMobile' => ['type' => 'boolean', 'label' => 'Reverse on Mobile'],
                    'leftContent' => ['type' => 'blocks', 'label' => 'Left Column Content'],
                    'rightContent' => ['type' => 'blocks', 'label' => 'Right Column Content'],
                ],
                'sort_order' => 2,
            ],
            [
                'name' => 'Spacer',
                'slug' => 'spacer',
                'category' => 'layout',
                'description' => 'Add vertical spacing between content blocks',
                'icon' => 'spacer',
                'vue_component' => 'SpacerSection.vue',
                'default_props' => [
                    'size' => 'medium',
                    'customHeight' => null,
                    'showLine' => false,
                    'lineColor' => '#e5e7eb',
                ],
                'prop_schema' => [
                    'size' => ['type' => 'select', 'label' => 'Size', 'options' => ['small', 'medium', 'large', 'xlarge']],
                    'customHeight' => ['type' => 'text', 'label' => 'Custom Height (e.g., 100px, 5rem)'],
                    'showLine' => ['type' => 'boolean', 'label' => 'Show Divider Line'],
                    'lineColor' => ['type' => 'color', 'label' => 'Line Color'],
                ],
                'sort_order' => 3,
            ],

            // Content components
            [
                'name' => 'Text Block',
                'slug' => 'text',
                'category' => 'content',
                'description' => 'A rich text content block',
                'icon' => 'type',
                'vue_component' => 'TextBlock.vue',
                'default_props' => [
                    'content' => '<p>Enter your content here...</p>',
                    'alignment' => 'left',
                ],
                'prop_schema' => [
                    'content' => ['type' => 'richtext', 'label' => 'Content'],
                    'alignment' => ['type' => 'select', 'label' => 'Alignment', 'options' => ['left', 'center', 'right']],
                ],
                'sort_order' => 1,
            ],
            [
                'name' => 'Heading',
                'slug' => 'heading',
                'category' => 'content',
                'description' => 'A heading element with customizable level',
                'icon' => 'heading',
                'vue_component' => 'Heading.vue',
                'default_props' => [
                    'text' => 'Section Heading',
                    'level' => 'h2',
                    'alignment' => 'left',
                ],
                'prop_schema' => [
                    'text' => ['type' => 'text', 'label' => 'Heading Text'],
                    'level' => ['type' => 'select', 'label' => 'Level', 'options' => ['h1', 'h2', 'h3', 'h4', 'h5', 'h6']],
                    'alignment' => ['type' => 'select', 'label' => 'Alignment', 'options' => ['left', 'center', 'right']],
                ],
                'sort_order' => 2,
            ],
            [
                'name' => 'Portfolio Item',
                'slug' => 'portfolio-item',
                'category' => 'content',
                'description' => 'A portfolio/project card with image, title, category, and hover effects',
                'icon' => 'folder',
                'vue_component' => 'PortfolioItem.vue',
                'default_props' => [
                    'image' => null,
                    'title' => 'Project Title',
                    'category' => 'Category',
                    'description' => 'A brief description of this project or work.',
                    'link' => '',
                    'linkText' => 'View Project',
                    'aspectRatio' => 'square',
                    'showOverlay' => true,
                    'overlayStyle' => 'gradient',
                ],
                'prop_schema' => [
                    'image' => ['type' => 'image', 'label' => 'Project Image'],
                    'title' => ['type' => 'text', 'label' => 'Title'],
                    'category' => ['type' => 'text', 'label' => 'Category/Tag'],
                    'description' => ['type' => 'textarea', 'label' => 'Description'],
                    'link' => ['type' => 'page_link', 'label' => 'Project Link'],
                    'linkText' => ['type' => 'text', 'label' => 'Link Text'],
                    'aspectRatio' => ['type' => 'select', 'label' => 'Aspect Ratio', 'options' => ['square', 'video', 'portrait', 'landscape']],
                    'showOverlay' => ['type' => 'boolean', 'label' => 'Show Hover Overlay'],
                    'overlayStyle' => ['type' => 'select', 'label' => 'Overlay Style', 'options' => ['gradient', 'solid', 'blur']],
                ],
                'sort_order' => 4,
            ],
            [
                'name' => 'Feature Grid',
                'slug' => 'features',
                'category' => 'content',
                'description' => 'A grid of features with icons and descriptions',
                'icon' => 'grid',
                'vue_component' => 'FeatureGrid.vue',
                'default_props' => [
                    'columns' => 3,
                    'features' => [
                        ['icon' => 'star', 'title' => 'Feature 1', 'description' => 'Description here'],
                        ['icon' => 'heart', 'title' => 'Feature 2', 'description' => 'Description here'],
                        ['icon' => 'check', 'title' => 'Feature 3', 'description' => 'Description here'],
                    ],
                ],
                'prop_schema' => [
                    'columns' => ['type' => 'select', 'label' => 'Columns', 'options' => [2, 3, 4]],
                    'features' => ['type' => 'repeater', 'label' => 'Features', 'fields' => [
                        'icon' => ['type' => 'icon', 'label' => 'Icon'],
                        'title' => ['type' => 'text', 'label' => 'Title'],
                        'description' => ['type' => 'textarea', 'label' => 'Description'],
                    ]],
                ],
                'sort_order' => 3,
            ],

            // Media components
            [
                'name' => 'Image',
                'slug' => 'image',
                'category' => 'media',
                'description' => 'A responsive image with optional caption',
                'icon' => 'image',
                'vue_component' => 'ImageBlock.vue',
                'default_props' => [
                    'src' => null,
                    'alt' => '',
                    'caption' => '',
                    'width' => '100%',
                    'rounded' => false,
                ],
                'prop_schema' => [
                    'src' => ['type' => 'image', 'label' => 'Image'],
                    'alt' => ['type' => 'text', 'label' => 'Alt Text'],
                    'caption' => ['type' => 'text', 'label' => 'Caption'],
                    'width' => ['type' => 'text', 'label' => 'Width'],
                    'rounded' => ['type' => 'boolean', 'label' => 'Rounded Corners'],
                ],
                'sort_order' => 1,
            ],
            [
                'name' => 'Image Gallery',
                'slug' => 'image-gallery',
                'category' => 'media',
                'description' => 'A gallery of images with lightbox support',
                'icon' => 'images',
                'vue_component' => 'ImageGallery.vue',
                'default_props' => [
                    'images' => [],
                    'columns' => 3,
                    'gap' => '1rem',
                ],
                'prop_schema' => [
                    'images' => ['type' => 'images', 'label' => 'Images'],
                    'columns' => ['type' => 'select', 'label' => 'Columns', 'options' => [2, 3, 4, 5]],
                    'gap' => ['type' => 'text', 'label' => 'Gap'],
                ],
                'sort_order' => 2,
            ],

            // Forms components
            [
                'name' => 'Contact Section',
                'slug' => 'contact-section',
                'category' => 'forms',
                'description' => 'Contact information display with optional contact form',
                'icon' => 'mail',
                'vue_component' => 'ContactSection.vue',
                'default_props' => [
                    'title' => 'Contact Us',
                    'email' => '',
                    'phone' => '',
                    'address' => '',
                    'hours' => '',
                    'showForm' => true,
                    'formFields' => ['name', 'email', 'message'],
                    'submitText' => 'Send Message',
                    'successMessage' => 'Thank you for your message! We\'ll get back to you soon.',
                    'recipientEmail' => '',
                ],
                'prop_schema' => [
                    'title' => ['type' => 'text', 'label' => 'Section Title'],
                    'email' => ['type' => 'text', 'label' => 'Display Email'],
                    'phone' => ['type' => 'text', 'label' => 'Display Phone'],
                    'address' => ['type' => 'textarea', 'label' => 'Display Address'],
                    'hours' => ['type' => 'text', 'label' => 'Business Hours'],
                    'showForm' => ['type' => 'boolean', 'label' => 'Show Contact Form'],
                    'formFields' => ['type' => 'checkboxes', 'label' => 'Form Fields', 'options' => ['name', 'email', 'phone', 'message']],
                    'submitText' => ['type' => 'text', 'label' => 'Submit Button Text'],
                    'successMessage' => ['type' => 'text', 'label' => 'Success Message'],
                    'recipientEmail' => ['type' => 'text', 'label' => 'Send Submissions To (Email)'],
                ],
                'sort_order' => 1,
            ],

            // Contact info display (no form)
            [
                'name' => 'Contact Info',
                'slug' => 'contact_info',
                'category' => 'forms',
                'description' => 'Display contact information (email, phone, address, hours)',
                'icon' => 'mail',
                'vue_component' => 'ContactSection.vue',
                'default_props' => [
                    'title' => 'Contact Information',
                    'email' => '',
                    'phone' => '',
                    'address' => '',
                    'hours' => '',
                    'showForm' => false,
                ],
                'prop_schema' => [
                    'title' => ['type' => 'text', 'label' => 'Section Title'],
                    'email' => ['type' => 'text', 'label' => 'Email'],
                    'phone' => ['type' => 'text', 'label' => 'Phone'],
                    'address' => ['type' => 'textarea', 'label' => 'Address'],
                    'hours' => ['type' => 'text', 'label' => 'Business Hours'],
                ],
                'sort_order' => 3,
            ],

            // Standalone contact form (for existing pages using contact_form slug)
            [
                'name' => 'Contact Form',
                'slug' => 'contact_form',
                'category' => 'forms',
                'description' => 'A standalone contact form',
                'icon' => 'mail',
                'vue_component' => 'ContactSection.vue',
                'default_props' => [
                    'title' => 'Send Us a Message',
                    'showForm' => true,
                    'fields' => ['name', 'email', 'message'],
                    'submit_text' => 'Send Message',
                    'successMessage' => 'Thank you for your message! We\'ll get back to you soon.',
                    'recipientEmail' => '',
                ],
                'prop_schema' => [
                    'title' => ['type' => 'text', 'label' => 'Form Title'],
                    'fields' => ['type' => 'checkboxes', 'label' => 'Form Fields', 'options' => ['name', 'email', 'phone', 'message']],
                    'submit_text' => ['type' => 'text', 'label' => 'Submit Button Text'],
                    'successMessage' => ['type' => 'text', 'label' => 'Success Message'],
                    'recipientEmail' => ['type' => 'text', 'label' => 'Send Submissions To (Email)'],
                ],
                'sort_order' => 2,
            ],

            // Marketing components
            [
                'name' => 'Call to Action',
                'slug' => 'call-to-action',
                'category' => 'marketing',
                'description' => 'A prominent call-to-action section',
                'icon' => 'megaphone',
                'vue_component' => 'CallToAction.vue',
                'default_props' => [
                    'heading' => 'Ready to get started?',
                    'description' => 'Join thousands of satisfied customers today.',
                    'buttonText' => 'Get Started',
                    'buttonLink' => '#',
                    'backgroundColor' => 'primary',
                ],
                'prop_schema' => [
                    'heading' => ['type' => 'text', 'label' => 'Heading'],
                    'description' => ['type' => 'textarea', 'label' => 'Description'],
                    'buttonText' => ['type' => 'text', 'label' => 'Button Text'],
                    'buttonLink' => ['type' => 'page_link', 'label' => 'Button Link'],
                    'backgroundColor' => ['type' => 'select', 'label' => 'Background Color', 'options' => ['primary', 'secondary', 'accent', 'dark']],
                ],
                'sort_order' => 1,
            ],
            [
                'name' => 'Testimonials',
                'slug' => 'testimonials',
                'category' => 'marketing',
                'description' => 'Customer testimonials in a carousel or grid',
                'icon' => 'quote',
                'vue_component' => 'Testimonials.vue',
                'default_props' => [
                    'layout' => 'grid',
                    'testimonials' => [
                        ['name' => 'John Doe', 'role' => 'CEO', 'content' => 'Amazing service!', 'avatar' => null],
                    ],
                ],
                'prop_schema' => [
                    'layout' => ['type' => 'select', 'label' => 'Layout', 'options' => ['grid', 'carousel']],
                    'testimonials' => ['type' => 'repeater', 'label' => 'Testimonials', 'fields' => [
                        'name' => ['type' => 'text', 'label' => 'Name'],
                        'role' => ['type' => 'text', 'label' => 'Role/Company'],
                        'content' => ['type' => 'textarea', 'label' => 'Testimonial'],
                        'avatar' => ['type' => 'image', 'label' => 'Avatar'],
                    ]],
                ],
                'sort_order' => 2,
            ],

            // Pricing component
            [
                'name' => 'Pricing Table',
                'slug' => 'pricing',
                'category' => 'marketing',
                'description' => 'Display pricing plans with features',
                'icon' => 'pricing',
                'vue_component' => 'PricingTable.vue',
                'default_props' => [
                    'plans' => [
                        [
                            'name' => 'Basic',
                            'price' => '$29',
                            'period' => '/month',
                            'description' => 'Perfect for getting started',
                            'features' => ['Feature 1', 'Feature 2', 'Feature 3'],
                            'featured' => false,
                        ],
                    ],
                ],
                'prop_schema' => [
                    'plans' => [
                        'type' => 'repeater',
                        'label' => 'Plans',
                        'fields' => [
                            'name' => ['type' => 'text', 'label' => 'Plan Name'],
                            'price' => ['type' => 'text', 'label' => 'Price'],
                            'period' => ['type' => 'text', 'label' => 'Period (e.g., /month)'],
                            'description' => ['type' => 'textarea', 'label' => 'Description'],
                            'features' => ['type' => 'stringlist', 'label' => 'Features'],
                            'featured' => ['type' => 'boolean', 'label' => 'Featured Plan'],
                        ],
                    ],
                ],
                'sort_order' => 3,
            ],

            // Commerce components
            [
                'name' => 'Product Card',
                'slug' => 'product-card',
                'category' => 'commerce',
                'description' => 'A product card with image, title, price, and buy button',
                'icon' => 'shopping-bag',
                'vue_component' => 'ProductCard.vue',
                'default_props' => [
                    'image' => null,
                    'title' => 'Product Title',
                    'description' => 'Product description goes here.',
                    'price' => '$99.00',
                    'priceId' => '',
                    'buttonText' => 'Buy Now',
                    'featured' => false,
                ],
                'prop_schema' => [
                    'image' => ['type' => 'image', 'label' => 'Product Image'],
                    'title' => ['type' => 'text', 'label' => 'Title'],
                    'description' => ['type' => 'textarea', 'label' => 'Description'],
                    'price' => ['type' => 'text', 'label' => 'Display Price'],
                    'priceId' => ['type' => 'text', 'label' => 'Stripe Price ID'],
                    'buttonText' => ['type' => 'text', 'label' => 'Button Text'],
                    'featured' => ['type' => 'boolean', 'label' => 'Featured Product'],
                ],
                'sort_order' => 1,
            ],
            [
                'name' => 'Checkout Button',
                'slug' => 'checkout-button',
                'category' => 'commerce',
                'description' => 'A button that initiates Stripe Checkout',
                'icon' => 'credit-card',
                'vue_component' => 'CheckoutButton.vue',
                'default_props' => [
                    'priceId' => '',
                    'quantity' => 1,
                    'buttonText' => 'Buy Now',
                    'buttonStyle' => 'primary',
                    'showQuantitySelector' => false,
                    'maxQuantity' => 10,
                ],
                'prop_schema' => [
                    'priceId' => ['type' => 'text', 'label' => 'Stripe Price ID'],
                    'quantity' => ['type' => 'number', 'label' => 'Default Quantity'],
                    'buttonText' => ['type' => 'text', 'label' => 'Button Text'],
                    'buttonStyle' => ['type' => 'select', 'label' => 'Button Style', 'options' => ['primary', 'secondary', 'accent']],
                    'showQuantitySelector' => ['type' => 'boolean', 'label' => 'Show Quantity Selector'],
                    'maxQuantity' => ['type' => 'number', 'label' => 'Max Quantity'],
                ],
                'sort_order' => 2,
            ],
            [
                'name' => 'Stripe Pricing Table',
                'slug' => 'stripe-pricing-table',
                'category' => 'commerce',
                'description' => 'Pricing table with Stripe Checkout integration',
                'icon' => 'table',
                'vue_component' => 'StripePricingTable.vue',
                'default_props' => [
                    'plans' => [
                        [
                            'name' => 'Basic',
                            'price' => '$29',
                            'period' => '/month',
                            'priceId' => '',
                            'description' => 'Perfect for getting started',
                            'features' => ['Feature 1', 'Feature 2', 'Feature 3'],
                            'featured' => false,
                            'buttonText' => 'Get Started',
                        ],
                    ],
                ],
                'prop_schema' => [
                    'plans' => [
                        'type' => 'repeater',
                        'label' => 'Plans',
                        'fields' => [
                            'name' => ['type' => 'text', 'label' => 'Plan Name'],
                            'price' => ['type' => 'text', 'label' => 'Display Price'],
                            'period' => ['type' => 'text', 'label' => 'Period (e.g., /month)'],
                            'priceId' => ['type' => 'text', 'label' => 'Stripe Price ID'],
                            'description' => ['type' => 'textarea', 'label' => 'Description'],
                            'features' => ['type' => 'stringlist', 'label' => 'Features'],
                            'featured' => ['type' => 'boolean', 'label' => 'Featured Plan'],
                            'buttonText' => ['type' => 'text', 'label' => 'Button Text'],
                        ],
                    ],
                ],
                'sort_order' => 3,
            ],

            // Sidebar components
            [
                'name' => 'Sidebar Card',
                'slug' => 'sidebar-card',
                'category' => 'sidebar',
                'description' => 'A simple card with title and content for sidebars',
                'icon' => 'card',
                'vue_component' => 'SidebarCard.vue',
                'default_props' => [
                    'title' => 'Card Title',
                    'content' => '<p>Card content goes here...</p>',
                    'variant' => 'bordered',
                ],
                'prop_schema' => [
                    'title' => ['type' => 'text', 'label' => 'Title'],
                    'content' => ['type' => 'richtext', 'label' => 'Content'],
                    'variant' => ['type' => 'select', 'label' => 'Style', 'options' => ['default', 'bordered', 'filled']],
                ],
                'sort_order' => 1,
            ],
            [
                'name' => 'Sidebar Contact',
                'slug' => 'sidebar-contact',
                'category' => 'sidebar',
                'description' => 'Contact information card for sidebars',
                'icon' => 'contact',
                'vue_component' => 'SidebarContact.vue',
                'default_props' => [
                    'title' => 'Contact Us',
                    'email' => '',
                    'phone' => '',
                    'address' => '',
                    'showIcons' => true,
                ],
                'prop_schema' => [
                    'title' => ['type' => 'text', 'label' => 'Title'],
                    'email' => ['type' => 'text', 'label' => 'Email'],
                    'phone' => ['type' => 'text', 'label' => 'Phone'],
                    'address' => ['type' => 'textarea', 'label' => 'Address'],
                    'showIcons' => ['type' => 'boolean', 'label' => 'Show Icons'],
                ],
                'sort_order' => 2,
            ],
            [
                'name' => 'Sidebar Links',
                'slug' => 'sidebar-links',
                'category' => 'sidebar',
                'description' => 'Quick links navigation for sidebars',
                'icon' => 'links',
                'vue_component' => 'SidebarLinks.vue',
                'default_props' => [
                    'title' => 'Quick Links',
                    'links' => [
                        ['text' => 'Home', 'url' => '/'],
                        ['text' => 'About', 'url' => '/about'],
                        ['text' => 'Contact', 'url' => '/contact'],
                    ],
                    'style' => 'list',
                ],
                'prop_schema' => [
                    'title' => ['type' => 'text', 'label' => 'Title'],
                    'links' => ['type' => 'repeater', 'label' => 'Links', 'fields' => [
                        'text' => ['type' => 'text', 'label' => 'Link Text'],
                        'url' => ['type' => 'page_link', 'label' => 'URL'],
                    ]],
                    'style' => ['type' => 'select', 'label' => 'Style', 'options' => ['list', 'buttons']],
                ],
                'sort_order' => 3,
            ],
            [
                'name' => 'Sidebar CTA',
                'slug' => 'sidebar-cta',
                'category' => 'sidebar',
                'description' => 'Call-to-action button for sidebars',
                'icon' => 'cta',
                'vue_component' => 'SidebarCTA.vue',
                'default_props' => [
                    'title' => 'Ready to Start?',
                    'description' => 'Get in touch with us today.',
                    'buttonText' => 'Contact Us',
                    'buttonLink' => '/contact',
                    'variant' => 'primary',
                ],
                'prop_schema' => [
                    'title' => ['type' => 'text', 'label' => 'Title'],
                    'description' => ['type' => 'textarea', 'label' => 'Description'],
                    'buttonText' => ['type' => 'text', 'label' => 'Button Text'],
                    'buttonLink' => ['type' => 'page_link', 'label' => 'Button Link'],
                    'variant' => ['type' => 'select', 'label' => 'Button Style', 'options' => ['primary', 'secondary', 'accent']],
                ],
                'sort_order' => 4,
            ],
            [
                'name' => 'Sidebar Image',
                'slug' => 'sidebar-image',
                'category' => 'sidebar',
                'description' => 'An image optimized for sidebars',
                'icon' => 'image',
                'vue_component' => 'SidebarImage.vue',
                'default_props' => [
                    'src' => null,
                    'alt' => '',
                    'caption' => '',
                    'rounded' => true,
                    'link' => '',
                ],
                'prop_schema' => [
                    'src' => ['type' => 'image', 'label' => 'Image'],
                    'alt' => ['type' => 'text', 'label' => 'Alt Text'],
                    'caption' => ['type' => 'text', 'label' => 'Caption'],
                    'rounded' => ['type' => 'boolean', 'label' => 'Rounded Corners'],
                    'link' => ['type' => 'page_link', 'label' => 'Link URL (optional)'],
                ],
                'sort_order' => 5,
            ],
            [
                'name' => 'Sidebar Spacer',
                'slug' => 'sidebar-spacer',
                'category' => 'sidebar',
                'description' => 'Add spacing between sidebar blocks',
                'icon' => 'spacer',
                'vue_component' => 'SidebarSpacer.vue',
                'default_props' => [
                    'size' => 'medium',
                    'showLine' => false,
                    'lineColor' => '#e5e7eb',
                ],
                'prop_schema' => [
                    'size' => ['type' => 'select', 'label' => 'Size', 'options' => ['small', 'medium', 'large']],
                    'showLine' => ['type' => 'boolean', 'label' => 'Show Divider Line'],
                    'lineColor' => ['type' => 'color', 'label' => 'Line Color'],
                ],
                'sort_order' => 6,
            ],

            // Product components
            [
                'name' => 'Product Image Gallery',
                'slug' => 'product-image-gallery',
                'category' => 'product',
                'description' => 'Image gallery with thumbnails, lightbox, and zoom (uses product gallery images)',
                'icon' => 'images',
                'vue_component' => 'ProductImageGallery.vue',
                'default_props' => [
                    'showThumbnails' => true,
                    'thumbnailPosition' => 'bottom',
                    'enableLightbox' => true,
                    'enableZoom' => true,
                ],
                'prop_schema' => [
                    'showThumbnails' => ['type' => 'boolean', 'label' => 'Show Thumbnails'],
                    'thumbnailPosition' => ['type' => 'select', 'label' => 'Thumbnail Position', 'options' => ['bottom', 'left', 'right']],
                    'enableLightbox' => ['type' => 'boolean', 'label' => 'Enable Lightbox'],
                    'enableZoom' => ['type' => 'boolean', 'label' => 'Enable Zoom'],
                ],
                'sort_order' => 1,
            ],
            [
                'name' => 'Add to Cart Button',
                'slug' => 'add-to-cart-button',
                'category' => 'product',
                'description' => 'Purchase button with quantity selector and Stripe integration',
                'icon' => 'shopping-cart',
                'vue_component' => 'AddToCartButton.vue',
                'default_props' => [
                    'buttonText' => 'Add to Cart',
                    'buttonStyle' => 'primary',
                    'showQuantitySelector' => true,
                    'minQuantity' => 1,
                    'maxQuantity' => 10,
                    'showPrice' => true,
                    'showStock' => true,
                ],
                'prop_schema' => [
                    'buttonText' => ['type' => 'text', 'label' => 'Button Text'],
                    'buttonStyle' => ['type' => 'select', 'label' => 'Button Style', 'options' => ['primary', 'secondary', 'accent']],
                    'showQuantitySelector' => ['type' => 'boolean', 'label' => 'Show Quantity Selector'],
                    'minQuantity' => ['type' => 'number', 'label' => 'Minimum Quantity'],
                    'maxQuantity' => ['type' => 'number', 'label' => 'Maximum Quantity'],
                    'showPrice' => ['type' => 'boolean', 'label' => 'Show Price'],
                    'showStock' => ['type' => 'boolean', 'label' => 'Show Stock Status'],
                ],
                'sort_order' => 2,
            ],
            [
                'name' => 'Related Products',
                'slug' => 'related-products',
                'category' => 'product',
                'description' => 'Display related products from category or manual selection',
                'icon' => 'grid',
                'vue_component' => 'RelatedProducts.vue',
                'default_props' => [
                    'title' => 'Related Products',
                    'source' => 'category',
                    'limit' => 4,
                    'columns' => 4,
                    'showPrice' => true,
                ],
                'prop_schema' => [
                    'title' => ['type' => 'text', 'label' => 'Section Title'],
                    'source' => ['type' => 'select', 'label' => 'Product Source', 'options' => ['category', 'featured', 'manual']],
                    'limit' => ['type' => 'number', 'label' => 'Number of Products'],
                    'columns' => ['type' => 'select', 'label' => 'Columns', 'options' => [2, 3, 4]],
                    'showPrice' => ['type' => 'boolean', 'label' => 'Show Prices'],
                ],
                'sort_order' => 3,
            ],
            [
                'name' => 'Product Reviews',
                'slug' => 'product-reviews',
                'category' => 'product',
                'description' => 'Customer reviews with ratings and submission form',
                'icon' => 'star',
                'vue_component' => 'ProductReviews.vue',
                'default_props' => [
                    'title' => 'Customer Reviews',
                    'allowSubmissions' => true,
                    'showRatingBreakdown' => true,
                    'reviewsPerPage' => 5,
                ],
                'prop_schema' => [
                    'title' => ['type' => 'text', 'label' => 'Section Title'],
                    'allowSubmissions' => ['type' => 'boolean', 'label' => 'Allow Submissions'],
                    'showRatingBreakdown' => ['type' => 'boolean', 'label' => 'Show Rating Breakdown'],
                    'reviewsPerPage' => ['type' => 'number', 'label' => 'Reviews Per Page'],
                ],
                'sort_order' => 4,
            ],
            [
                'name' => 'Appointment Picker',
                'slug' => 'appointment-picker',
                'category' => 'product',
                'description' => 'Service booking with calendar and time slot selection',
                'icon' => 'calendar',
                'vue_component' => 'AppointmentPicker.vue',
                'default_props' => [
                    'title' => 'Book an Appointment',
                    'serviceType' => '',
                    'duration' => 60,
                    'availableDays' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
                    'startTime' => '09:00',
                    'endTime' => '17:00',
                    'slotInterval' => 30,
                    'maxAdvanceDays' => 30,
                ],
                'prop_schema' => [
                    'title' => ['type' => 'text', 'label' => 'Section Title'],
                    'serviceType' => ['type' => 'text', 'label' => 'Service Type'],
                    'duration' => ['type' => 'number', 'label' => 'Duration (minutes)'],
                    'availableDays' => ['type' => 'checkboxes', 'label' => 'Available Days', 'options' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']],
                    'startTime' => ['type' => 'text', 'label' => 'Start Time'],
                    'endTime' => ['type' => 'text', 'label' => 'End Time'],
                    'slotInterval' => ['type' => 'number', 'label' => 'Slot Interval (minutes)'],
                    'maxAdvanceDays' => ['type' => 'number', 'label' => 'Max Advance Days'],
                ],
                'sort_order' => 6,
            ],
            [
                'name' => 'Product Specifications',
                'slug' => 'product-specifications',
                'category' => 'product',
                'description' => 'Specifications table with key-value pairs',
                'icon' => 'list',
                'vue_component' => 'ProductSpecifications.vue',
                'default_props' => [
                    'title' => 'Specifications',
                    'layout' => 'table',
                    'specifications' => [
                        ['label' => 'Material', 'value' => ''],
                        ['label' => 'Dimensions', 'value' => ''],
                        ['label' => 'Weight', 'value' => ''],
                    ],
                ],
                'prop_schema' => [
                    'title' => ['type' => 'text', 'label' => 'Section Title'],
                    'layout' => ['type' => 'select', 'label' => 'Layout', 'options' => ['table', 'list', 'grid']],
                    'specifications' => ['type' => 'repeater', 'label' => 'Specifications', 'fields' => [
                        'label' => ['type' => 'text', 'label' => 'Label'],
                        'value' => ['type' => 'text', 'label' => 'Value'],
                    ]],
                ],
                'sort_order' => 7,
            ],
            [
                'name' => 'Stock Status',
                'slug' => 'stock-status',
                'category' => 'product',
                'description' => 'Product availability indicator',
                'icon' => 'check-circle',
                'vue_component' => 'StockStatus.vue',
                'default_props' => [
                    'showIcon' => true,
                    'showLabel' => true,
                    'lowStockThreshold' => 5,
                    'inStockText' => 'In Stock',
                    'lowStockText' => 'Low Stock',
                    'outOfStockText' => 'Out of Stock',
                ],
                'prop_schema' => [
                    'showIcon' => ['type' => 'boolean', 'label' => 'Show Icon'],
                    'showLabel' => ['type' => 'boolean', 'label' => 'Show Label'],
                    'lowStockThreshold' => ['type' => 'number', 'label' => 'Low Stock Threshold'],
                    'inStockText' => ['type' => 'text', 'label' => 'In Stock Text'],
                    'lowStockText' => ['type' => 'text', 'label' => 'Low Stock Text'],
                    'outOfStockText' => ['type' => 'text', 'label' => 'Out of Stock Text'],
                ],
                'sort_order' => 8,
            ],
        ];

        foreach ($components as $component) {
            PageComponent::updateOrCreate(
                ['slug' => $component['slug']],
                $component
            );
        }
    }
}
